/**
 * test_wasp_filter.cpp — Behavioral tests for src/vespid/WaspFilter.hpp
 *
 * TDD behavioral suite for the Wasp VCF nonlinear core (Task 3).  The core is
 * driven directly at fsInt = 192000 (standing in for 48 kHz host x 4), no
 * resamplers.  Controls are wired exactly like wasp_ref.py's set_controls:
 *     fci = clamp(fc*wcComp, 0.25, 0.45*fsInt)
 *     g   = tan(pi*fci/fsInt)
 *     wci = 2*pi*fci
 *     kC2 = R3*C2*wci - kR2*wci/(2*pi*fPole)   (may be negative)
 *     h1  = computeH1(rho, fsInt)
 *
 * Golden numbers are the committed values in tests/vespid_ref/golden.json
 * (generated by wasp_ref.py at 48 kHz x8 = 384 kHz with the brentq solver).
 * They are RAW states (pre-makeup, pre-DC-blocker): small-signal on raw LP,
 * self-osc amplitude on raw BP.  We therefore measure WaspFilter::raw().
 *
 * Compile & run (or via tests/run.sh):
 *   g++ -std=c++20 -O2 -I../src -o test_wasp_filter test_wasp_filter.cpp && ./test_wasp_filter
 */

#include "../../src/vespid/WaspFilter.hpp"
#include <cmath>
#include <cstdio>
#include <vector>

// ── Test harness ──────────────────────────────────────────────────────────
static int sPassed = 0, sFailed = 0;
static void report(bool ok, const char* name, const char* detail = nullptr) {
    if (ok) { printf("  PASS  %s\n", name); ++sPassed; }
    else {
        printf("  FAIL  %s", name);
        if (detail) printf("  (%s)", detail);
        printf("\n"); ++sFailed;
    }
}

// ── Golden values (tests/vespid_ref/golden.json, committed) ──────────
namespace golden {
    constexpr double lp_db_fc1000_f250  = -10.85872137533553;
    constexpr double lp_db_fc200_f50    = -11.629347066778603;
    constexpr double lp_db_fc5000_f1250 = -10.815114975273858;
    constexpr double peak_rho0          = -3.680627952481146;
    constexpr double peak_rho05         =  5.697700974461849;
    constexpr double peak_rho09         = 19.117297378707118;
    constexpr double selfosc_scr_amp    =  2.660487531261526;
    constexpr double selfosc_scr_freq   =  716.7785234899329;
    constexpr double selfosc_tame_amp   =  2.3440569068947336e-12;
}

// ── Control wiring (matches wasp_ref.py set_controls) ──────────────────────
static constexpr float kFsInt = 192000.f;   // 48 kHz x4 (brief)
static constexpr float kPi    = 3.14159265358979323846f;
static constexpr float kFPole = 80000.f;
static constexpr float kR3C2  = 27e3f * 100e-12f;   // 2.7e-6

struct Controls { float g; float kC2; wasp::H1Coeffs h1; };

static Controls makeControls(const wasp::ModeConfig& m, float fc, float rho) {
    float fci = fc * m.wcComp;
    float lo = 0.25f, hi = 0.45f * kFsInt;
    if (fci < lo) fci = lo;
    if (fci > hi) fci = hi;
    float g   = std::tan(kPi * fci / kFsInt);
    float wci = 2.f * kPi * fci;
    float kC2 = kR3C2 * wci - m.kR2 * wci / (2.f * kPi * kFPole);
    wasp::H1Coeffs h1 = wasp::computeH1(rho < 0.f ? 0.f : (rho > 1.f ? 1.f : rho), kFsInt);
    return { g, kC2, h1 };
}

// ── Small-signal RMS-ratio LP response (matches response_db) ───────────────
static double smallSignalLpDb(const wasp::ModeConfig& m, float fc, float rho,
                              float fprobe, float amp, bool highAcc = true) {
    wasp::WaspFilter w; w.setSampleRate(kFsInt); w.setMode(m); w.reset();
    Controls c = makeControls(m, fc, rho);
    const int n = (int)(kFsInt * 0.5f);
    std::vector<float> y(n);
    for (int i = 0; i < n; ++i) {
        float x = amp * std::sin(2.f * kPi * fprobe * (float)i / kFsInt);
        w.process(x, c.g, c.h1, c.kC2, highAcc);
        y[i] = w.raw().lp;
    }
    // RMS over 2nd half (mean removed like std) vs input RMS
    double sumY = 0, sumY2 = 0; int cnt = 0;
    for (int i = n / 2; i < n; ++i) { sumY += y[i]; sumY2 += (double)y[i]*y[i]; ++cnt; }
    double meanY = sumY / cnt;
    double stdY = std::sqrt(sumY2 / cnt - meanY * meanY);
    double stdRef = amp / std::sqrt(2.0);   // std of a unit-amp sine = amp/sqrt2
    return 20.0 * std::log10((std::sqrt(2.0) * stdY + 1e-12) / (std::sqrt(2.0) * stdRef));
}

// Same, but returns the makeup'd + DC-blocked output (for HP passband/makeup).
static double smallSignalDb(const wasp::ModeConfig& m, float fc, float rho,
                            float fprobe, float amp, int which /*0=lp,1=bp,2=hp*/) {
    wasp::WaspFilter w; w.setSampleRate(kFsInt); w.setMode(m); w.reset();
    Controls c = makeControls(m, fc, rho);
    const int n = (int)(kFsInt * 0.5f);
    std::vector<float> y(n);
    for (int i = 0; i < n; ++i) {
        float x = amp * std::sin(2.f * kPi * fprobe * (float)i / kFsInt);
        wasp::WaspFilter::Out o = w.process(x, c.g, c.h1, c.kC2, true);
        y[i] = which == 0 ? o.lp : (which == 1 ? o.bp : o.hp);
    }
    double sumY = 0, sumY2 = 0; int cnt = 0;
    for (int i = n / 2; i < n; ++i) { sumY += y[i]; sumY2 += (double)y[i]*y[i]; ++cnt; }
    double meanY = sumY / cnt;
    double stdY = std::sqrt(sumY2 / cnt - meanY * meanY);
    double stdRef = amp / std::sqrt(2.0);
    return 20.0 * std::log10((std::sqrt(2.0) * stdY + 1e-12) / (std::sqrt(2.0) * stdRef));
}

// ── Self-oscillation probe (matches selfosc_probe) ─────────────────────────
// Kick 0.1 s of 3 V sine at fc, then silence; measure raw BP tail (last 0.25 s):
// amplitude = sqrt(2)*std(mean-removed), frequency = positive-going zero xings.
struct SelfOsc { double amp; double freq; bool finite; };
static SelfOsc selfOsc(const wasp::ModeConfig& m, float fc, float rho, float dur) {
    wasp::WaspFilter w; w.setSampleRate(kFsInt); w.setMode(m); w.reset();
    Controls c = makeControls(m, fc, rho);
    const int n = (int)(kFsInt * dur);
    const int kick = (int)(kFsInt * 0.1f);
    std::vector<float> bp(n);
    bool finite = true;
    for (int i = 0; i < n; ++i) {
        float x = (i < kick) ? 3.f * std::sin(2.f * kPi * fc * (float)i / kFsInt) : 0.f;
        w.process(x, c.g, c.h1, c.kC2, true);
        bp[i] = w.raw().bp;
        if (!std::isfinite(bp[i])) finite = false;
    }
    int t0 = n - (int)(kFsInt * 0.25f);
    double sum = 0; int cnt = 0;
    for (int i = t0; i < n; ++i) { sum += bp[i]; ++cnt; }
    double mean = sum / cnt;
    double s2 = 0;
    for (int i = t0; i < n; ++i) { double d = bp[i] - mean; s2 += d * d; }
    double amp = std::sqrt(2.0) * std::sqrt(s2 / cnt);
    // positive-going zero crossings on the mean-removed tail
    std::vector<int> zc;
    for (int i = t0 + 1; i < n; ++i) {
        double a = bp[i - 1] - mean, b = bp[i] - mean;
        if (a <= 0 && b > 0) zc.push_back(i - t0);
    }
    double freq = 0;
    if ((int)zc.size() > 3)
        freq = kFsInt * (double)(zc.size() - 1) / (double)(zc.back() - zc.front());
    return { amp, freq, finite };
}

static bool withinDb(double a, double b, double tol) { return std::fabs(a - b) <= tol; }

// ── Tests ──────────────────────────────────────────────────────────────────
static void test_small_signal() {
    printf("\n1. Small-signal LP passband (rho=0.3, 50 mV probe) vs golden (+/-1.5 dB)\n");
    struct C { float fc, fp; double gold; const char* tag; };
    C cs[] = {
        { 1000.f, 250.f,  golden::lp_db_fc1000_f250,  "fc1000 f250" },
        {  200.f,  50.f,  golden::lp_db_fc200_f50,    "fc200 f50"   },
        { 5000.f, 1250.f, golden::lp_db_fc5000_f1250, "fc5000 f1250"},
    };
    for (auto& c : cs) {
        double db = smallSignalLpDb(wasp::kScreaming, c.fc, 0.3f, c.fp, 0.05f);
        char buf[128];
        snprintf(buf, sizeof(buf), "%s got=%.3f dB golden=%.3f dB", c.tag, db, c.gold);
        report(withinDb(db, c.gold, 1.5), "LP small-signal within 1.5 dB of golden", buf);
    }
}

static void test_rolloff() {
    printf("\n2. LP rolloff: gain at 3*fc >= 9 dB below passband\n");
    double pass = smallSignalLpDb(wasp::kScreaming, 1000.f, 0.3f, 250.f, 0.05f);
    double roll = smallSignalLpDb(wasp::kScreaming, 1000.f, 0.3f, 3000.f, 0.05f);
    char buf[128];
    snprintf(buf, sizeof(buf), "passband(250)=%.2f dB, 3fc(3000)=%.2f dB, drop=%.2f dB",
             pass, roll, pass - roll);
    report((pass - roll) >= 9.0, "LP rolloff at 3*fc is >= 9 dB below passband", buf);
}

static void test_resonance_monotone() {
    printf("\n3. Resonance peak grows with rho (fc=1000, 20 mV probe)\n");
    double p0 = smallSignalLpDb(wasp::kScreaming, 1000.f, 0.0f, 1000.f, 0.02f);
    double p5 = smallSignalLpDb(wasp::kScreaming, 1000.f, 0.5f, 1000.f, 0.02f);
    double p9 = smallSignalLpDb(wasp::kScreaming, 1000.f, 0.9f, 1000.f, 0.02f);
    char buf[160];
    snprintf(buf, sizeof(buf), "rho0=%.2f rho0.5=%.2f rho0.9=%.2f (golden %.2f/%.2f/%.2f)",
             p0, p5, p9, golden::peak_rho0, golden::peak_rho05, golden::peak_rho09);
    report(p5 > p0 + 0.5 && p9 > p5 + 0.5, "resonance peak strictly increasing in rho", buf);
    report(withinDb(p0, golden::peak_rho0, 2.0), "peak rho=0 within 2 dB of golden", buf);
    report(withinDb(p5, golden::peak_rho05, 2.0), "peak rho=0.5 within 2 dB of golden", buf);
    report(withinDb(p9, golden::peak_rho09, 2.0), "peak rho=0.9 within 2 dB of golden", buf);
}

static void test_selfosc_screaming() {
    printf("\n4. Screaming self-oscillation (fc=1000, rho=1)\n");
    SelfOsc s = selfOsc(wasp::kScreaming, 1000.f, 1.0f, 2.0f);
    double lo = std::max(0.5 * golden::selfosc_scr_amp, 0.5);
    double hiA = 1.5 * golden::selfosc_scr_amp;
    char buf[160];
    snprintf(buf, sizeof(buf), "amp=%.3f V (want [%.3f,%.3f]) freq=%.1f Hz (golden %.1f)",
             s.amp, lo, hiA, s.freq, golden::selfosc_scr_freq);
    report(s.finite, "self-osc outputs all finite", buf);
    report(s.amp >= lo && s.amp <= hiA, "self-osc amplitude within [0.5x,1.5x] golden", buf);
    double fTol = 0.15 * golden::selfosc_scr_freq;
    report(std::fabs(s.freq - golden::selfosc_scr_freq) <= fTol,
           "self-osc frequency within 15% of golden", buf);
}

static void test_tame_ringout() {
    printf("\n5. Tame rings out (fc=1000, rho=1) tail < 0.05 V\n");
    SelfOsc s = selfOsc(wasp::kTame, 1000.f, 1.0f, 2.0f);
    char buf[128];
    snprintf(buf, sizeof(buf), "tame tail amp=%.6g V (want < 0.05)", s.amp);
    report(s.finite && s.amp < 0.05, "Tame does not free-run (tail < 0.05 V)", buf);
}

static void test_boundedness() {
    printf("\n6. Boundedness: 80 V square @30 Hz, fc=20 kHz knob, rho=1, 2 s\n");
    // Boundedness is a no-blow-up / rail-bounded check. The RAW filter states
    // are the physical quantity the "< 15 V" bound describes: they are clamped
    // to the inverter/rail range and must stay finite and bounded. The MAKEUP'D
    // outputs can transiently reach ~20 V here (the asymmetric inverter rail
    // -vLo = -8.5 V plus an integrator increment, times the x2.0 Screaming
    // makeup), under this deliberately extreme 80 V overdrive — that is
    // expected, not a divergence. We therefore assert: makeup'd outputs FINITE
    // (the stability guarantee) and raw states bounded < 15 V (rail-bounded).
    wasp::WaspFilter w; w.setSampleRate(kFsInt); w.setMode(wasp::kScreaming); w.reset();
    Controls c = makeControls(wasp::kScreaming, 20000.f, 1.0f);
    const int n = (int)(kFsInt * 2.f);
    bool finite = true; float rawPeak = 0.f, outPeak = 0.f;
    for (int i = 0; i < n; ++i) {
        float phase = std::fmod(30.f * (float)i / kFsInt, 1.f);
        float sq = (phase < 0.5f) ? 1.f : -1.f;
        float x = 8.f * 10.f * sq;   // 10 V square x8 drive-equivalent
        wasp::WaspFilter::Out o = w.process(x, c.g, c.h1, c.kC2, true);
        wasp::WaspFilter::Out r = w.raw();
        rawPeak = std::max({rawPeak, std::fabs(r.lp), std::fabs(r.bp), std::fabs(r.hp)});
        outPeak = std::max({outPeak, std::fabs(o.lp), std::fabs(o.bp), std::fabs(o.hp)});
        if (!std::isfinite(o.lp) || !std::isfinite(o.bp) || !std::isfinite(o.hp)) finite = false;
    }
    if (!w.stateFinite()) finite = false;
    char buf[160];
    snprintf(buf, sizeof(buf), "raw peak=%.3f V (rail-bounded, want < 15); makeup'd peak=%.3f V finite=%d",
             rawPeak, outPeak, (int)finite);
    report(finite && rawPeak < 15.f, "states finite and rail-bounded (< 15 V) under overdrive", buf);
}

static void test_hp_bp_sanity() {
    printf("\n7. HP/BP sanity\n");
    // BP peaks near fc
    double bpLo  = smallSignalDb(wasp::kScreaming, 1000.f, 0.5f, 250.f, 0.02f, 1);
    double bpMid = smallSignalDb(wasp::kScreaming, 1000.f, 0.5f, 1000.f, 0.02f, 1);
    double bpHi  = smallSignalDb(wasp::kScreaming, 1000.f, 0.5f, 4000.f, 0.02f, 1);
    char buf[160];
    snprintf(buf, sizeof(buf), "BP: 250=%.2f  1000=%.2f  4000=%.2f dB", bpLo, bpMid, bpHi);
    report(bpMid > bpLo && bpMid > bpHi, "BP peaks near fc", buf);
    // HP passband (probe 8*fc). The brief's target is "unity*makeup", but the
    // Rev-1 loop-gain factor lambda = invA0/(nInv+invA0) scales the HP passband
    // just as it costs the LP passband its gain (spec Revision 1): in the
    // small-signal limit the feedback terms vanish and hp -> -lambda*hin, so the
    // HP passband gain is lambda*makeup, not unity*makeup. Verified: HP asymptotes
    // to 3.26 dB = 20log10(lambda*makeup) as probe freq rises (3.29 dB @16fc,
    // 3.26 dB @60fc). We assert against the physically-correct lambda*makeup.
    double lambda = wasp::kScreaming.invA0 / (wasp::kScreaming.nInv + wasp::kScreaming.invA0);
    double hp = smallSignalDb(wasp::kScreaming, 1000.f, 0.3f, 8000.f, 0.05f, 2);
    double wantHp = 20.0 * std::log10(lambda * wasp::kScreaming.makeup);
    char buf2[160];
    snprintf(buf2, sizeof(buf2), "HP@8fc=%.2f dB, want %.2f (lambda*makeup) +/-2.5", hp, wantHp);
    report(withinDb(hp, wantHp, 2.5), "HP passband within 2.5 dB of lambda*makeup", buf2);
}

static void test_dc_block() {
    printf("\n8. DC block: 2 V DC in, LP output mean over last 0.5 s < 0.05 V\n");
    wasp::WaspFilter w; w.setSampleRate(kFsInt); w.setMode(wasp::kScreaming); w.reset();
    Controls c = makeControls(wasp::kScreaming, 1000.f, 0.3f);
    const int n = (int)(kFsInt * 2.f);
    double sum = 0; int cnt = 0;
    for (int i = 0; i < n; ++i) {
        wasp::WaspFilter::Out o = w.process(2.f, c.g, c.h1, c.kC2, true);
        if (i >= n - (int)(kFsInt * 0.5f)) { sum += o.lp; ++cnt; }
    }
    double mean = sum / cnt;
    char buf[96];
    snprintf(buf, sizeof(buf), "LP mean = %.6f V (want < 0.05)", mean);
    report(std::fabs(mean) < 0.05, "DC blocked at LP output", buf);
}

static void test_highacc_consistency() {
    printf("\n9. highAcc vs standard: small-signal differs by < 0.5 dB\n");
    double hi = smallSignalLpDb(wasp::kScreaming, 1000.f, 0.3f, 250.f, 0.05f, true);
    double st = smallSignalLpDb(wasp::kScreaming, 1000.f, 0.3f, 250.f, 0.05f, false);
    char buf[128];
    snprintf(buf, sizeof(buf), "highAcc=%.3f standard=%.3f dB diff=%.3f", hi, st, hi - st);
    report(std::fabs(hi - st) < 0.5, "highAcc and standard agree within 0.5 dB", buf);
}

// THD (h2..h12 vs h1) and fundamental of raw LP for a 5 V, 110 Hz sine
// scaled by `gain` — the drive-staging measurement from
// docs/superpowers/specs/2026-07-19-vespid-drive-remap-design.md.
struct Thd { double fund; double thd; bool finite; };
static Thd thdAtGain(const wasp::ModeConfig& m, float gain, float fc, float rho) {
    const float f0 = 110.f, amp = 5.f;
    wasp::WaspFilter w; w.setSampleRate(kFsInt); w.setMode(m); w.reset();
    Controls c = makeControls(m, fc, rho);
    int per = (int)std::round(kFsInt / f0);
    int nSettle = per * 20, nMeas = per * 40;
    std::vector<double> y(nMeas);
    bool finite = true;
    for (int i = 0; i < nSettle + nMeas; ++i) {
        float x = amp * gain * std::sin(2.f * kPi * f0 * (float)i / kFsInt);
        w.process(x, c.g, c.h1, c.kC2, true);
        float lp = w.raw().lp;
        if (!std::isfinite(lp)) finite = false;
        if (i >= nSettle) y[i - nSettle] = lp;
    }
    double hmag[13] = {};
    for (int h = 1; h <= 12; ++h) {
        double re = 0, im = 0, wf = 2.0 * M_PI * h * f0 / kFsInt;
        for (int i = 0; i < nMeas; ++i) {
            re += y[i] * std::cos(wf * i);
            im += y[i] * std::sin(wf * i);
        }
        hmag[h] = 2.0 * std::sqrt(re * re + im * im) / nMeas;
    }
    double hs2 = 0;
    for (int h = 2; h <= 12; ++h) hs2 += hmag[h] * hmag[h];
    return { hmag[1], std::sqrt(hs2) / (hmag[1] + 1e-30), finite };
}

static void test_drive_staging() {
    printf("\n10. Drive staging (5 V input): 2x clean, 64x clipped, level monotone\n");
    // Effective gains at the ends of the Vespid drive knob (2*2^(5*d), d=0/1).
    Thd lo = thdAtGain(wasp::kScreaming, 2.f, 1000.f, 0.3f);
    Thd hi = thdAtGain(wasp::kScreaming, 64.f, 1000.f, 0.3f);
    char buf[160];
    snprintf(buf, sizeof(buf), "2x: fund=%.3f V THD=%.3f%%; 64x: fund=%.3f V THD=%.2f%%",
             lo.fund, 100 * lo.thd, hi.fund, 100 * hi.thd);
    report(lo.finite && hi.finite, "drive extremes finite", buf);
    report(lo.thd < 0.01, "drive floor (2x) is clean (THD < 1%)", buf);
    report(hi.thd > 0.10, "drive ceiling (64x) is clipped (THD > 10%)", buf);
    report(hi.fund > lo.fund, "fundamental rises from floor to ceiling", buf);
    report(hi.fund < 15.0, "raw LP fundamental rail-bounded at 64x", buf);
}

static void test_mode_input_staging() {
    printf("\n11. Per-mode input staging (drive-0 operating points)\n");
    // Effective drive-0 levels from Vespid.cpp: 5 V host signal x 2x floor
    // x mode.inGain -> Screaming 10 V (Euro-hot, clean), Tame 2.5 V (EDP
    // nominal: the original's light rasp, ~12% THD at fc=1500, rho=0.225).
    // Calibration: 2026-07-19-vespid-input-calibration-design.md.
    Thd scr  = thdAtGain(wasp::kScreaming, 2.f,  1500.f, 0.225f);
    Thd tame = thdAtGain(wasp::kTame,      0.5f, 1500.f, 0.225f);
    char buf[160];
    snprintf(buf, sizeof(buf), "Screaming@10V: THD=%.3f%%; Tame@2.5V: THD=%.2f%%",
             100 * scr.thd, 100 * tame.thd);
    report(scr.finite && tame.finite, "staged operating points finite", buf);
    report(scr.thd < 0.01, "Screaming drive-0 (10 V eq.) is clean (THD < 1%)", buf);
    report(tame.thd > 0.05 && tame.thd < 0.20,
           "Tame drive-0 (2.5 V eq.) has the EDP light rasp (THD 5-20%)", buf);
}

// Controls at an explicit fPole (makeControls is fixed at kFPole=80k).
static Controls makeControlsFp(const wasp::ModeConfig& m, float fc, float rho,
                               float fPole) {
    Controls c = makeControls(m, fc, rho);
    float fci = fc * m.wcComp;
    if (fci < 0.25f) fci = 0.25f;
    if (fci > 0.45f * kFsInt) fci = 0.45f * kFsInt;
    float wci = 2.f * kPi * fci;
    c.kC2 = kR3C2 * wci - m.kR2 * wci / (2.f * kPi * fPole);
    return c;
}

static void test_selfosc_onset() {
    printf("\n12. Self-osc onset & baked-fPole guards (1e-4 noise seed, from silence)\n");
    // Baked per-mode inverter bandwidth (Vespid.cpp kFPoleScreaming/
    // kFPoleTame): Screaming at 50 kHz must start screaming in musical time
    // from the module's noise seed alone; Tame at 60 kHz must never
    // free-run. Calibration: 2026-07-19-vespid-selfosc-onset-design.md.
    {
        Controls c = makeControlsFp(wasp::kScreaming, 1000.f, 1.f, 50000.f);
        wasp::WaspFilter w; w.setSampleRate(kFsInt);
        w.setMode(wasp::kScreaming); w.reset();
        const int n = (int)(kFsInt * 3.f);
        float d = 1e-4f; double onset = -1; float peak = 0.f;
        for (int i = 0; i < n; ++i) {
            d = -d;
            w.process(d, c.g, c.h1, c.kC2, true);
            float bp = std::fabs(w.raw().bp);
            peak = std::max(peak, bp);
            if (onset < 0 && bp > 1.f) onset = (double)i / kFsInt;
        }
        char buf[128];
        snprintf(buf, sizeof(buf), "onset=%.3f s (want < 1.0), peak=%.2f V", onset, peak);
        report(onset >= 0 && onset < 1.0,
               "Screaming @50 kHz (baked) self-oscillates within 1 s of silence", buf);
    }
    {
        Controls c = makeControlsFp(wasp::kTame, 1000.f, 1.f, 60000.f);
        wasp::WaspFilter w; w.setSampleRate(kFsInt);
        w.setMode(wasp::kTame); w.reset();
        const int n = (int)(kFsInt * 4.f);
        int t0 = n - (int)(kFsInt * 0.5f);   // tail amplitude over the last 0.5 s
        double sum2 = 0; int cnt = 0; float d = 1e-4f;
        for (int i = 0; i < n; ++i) {
            d = -d;
            w.process(d, c.g, c.h1, c.kC2, true);
            if (i >= t0) { double v = w.raw().bp; sum2 += v * v; ++cnt; }
        }
        double amp = std::sqrt(2.0 * sum2 / cnt);
        char buf[128];
        snprintf(buf, sizeof(buf), "tail amp=%.6g V (want < 0.05)", amp);
        report(amp < 0.05, "Tame @60 kHz (baked) does not free-run from noise seed", buf);
    }
}

int main() {
    printf("Wasp filter behavioral test suite\n");
    printf("=================================\n");
    test_small_signal();
    test_rolloff();
    test_resonance_monotone();
    test_selfosc_screaming();
    test_tame_ringout();
    test_boundedness();
    test_hp_bp_sanity();
    test_dc_block();
    test_highacc_consistency();
    test_drive_staging();
    test_mode_input_staging();
    test_selfosc_onset();
    printf("\n=================================\n");
    printf("%d passed, %d failed\n", sPassed, sFailed);
    return sFailed > 0 ? 1 : 0;
}
