#pragma once
// wasp_dsp_utils.hpp — shared math for the Yellowjacket Wasp VCF core.
// Constants and derivations: docs/superpowers/specs/2026-07-15-yellowjacket-*.md
#include <cmath>
#include <algorithm>

namespace wasp {

// tanh approximant x*(27+x^2)/(27+9x^2), exact-valued and slope-continuous
// at the |x|=3 handoff to +/-1 (tanh(3)=0.995).
inline float tanhApprox(float x) {
    if (x >  3.f) return 1.f;
    if (x < -3.f) return -1.f;
    float x2 = x*x;
    return x*(27.f + x2)/(27.f + 9.f*x2);
}
// tanh(x)/x with the same regions; limit 1 at 0.
inline float tanhXdX(float x) {
    float ax = std::fabs(x);
    if (ax > 3.f) return 1.f/ax;
    float x2 = x*x;
    return (27.f + x2)/(27.f + 9.f*x2);
}

// H1(s) resonance-network pole-zero, Delta-Y closed form (research notes),
// bilinear-transformed at the internal rate. rho = resonance pot 0..1.
struct H1Coeffs { float beta0, beta1, alpha1; };
inline H1Coeffs computeH1(float rho, float fsInt) {
    constexpr float R3=27e3f, R4=27e3f, R13=1e6f, R14=1e3f, R15=100e3f,
                    Rres=50e3f, C7=0.22e-6f;
    float s1 = rho*Rres + R14, s2 = (1.f-rho)*Rres, s3 = R13 + R15;
    float tot = s1 + s2 + s3;
    float Ra = s1*s3/tot, Rb = s2*s3/tot, Rc = s1*s2/tot;
    float Za = Ra, Zc = Rc + R4;
    float b1 = R3*Rb*C7, b0 = R3;
    float a1 = C7*(Rb*(Za+Zc) + Za*Zc), a0 = Za + Zc;
    float K = 2.f*fsInt, d = a0 + a1*K;
    return { (b0 + b1*K)/d, (b0 - b1*K)/d, (a0 - a1*K)/d };
}

// One-pole DC blocker (~8 Hz default).
struct DcBlocker {
    float state = 0.f, a = 0.001f;
    void setSampleRate(float fs) { a = 1.f - std::exp(-2.f*float(M_PI)*8.f/fs); }
    void reset() { state = 0.f; }
    float process(float x) { float y = x - state; state += a*y; return y; }
};

// 47-tap FIR halfband pair (taps generated by tests/yellowjacket_ref, Task 1;
// 31 taps could not reach the 70 dB stopband — see fitted_constants.md).
// kHalfbandTaps: the 47-tap primary array from fitted_constants.md.
inline constexpr int kHbN = 47;
inline constexpr float kHalfbandTaps[kHbN] = {
    -3.43387434e-04f, 0.00000000e+00f, 8.44199816e-04f, 0.00000000e+00f,
    -1.80075410e-03f, 0.00000000e+00f, 3.39305781e-03f, 0.00000000e+00f,
    -5.86633996e-03f, 0.00000000e+00f, 9.56558679e-03f, 0.00000000e+00f,
    -1.49720535e-02f, 0.00000000e+00f, 2.29213469e-02f, 0.00000000e+00f,
    -3.50925691e-02f, 0.00000000e+00f, 5.58476697e-02f, 0.00000000e+00f,
    -1.01243801e-01f, 0.00000000e+00f, 3.16662350e-01f, 4.99950856e-01f,
    3.16662350e-01f, 0.00000000e+00f, -1.01243801e-01f, 0.00000000e+00f,
    5.58476697e-02f, 0.00000000e+00f, -3.50925691e-02f, 0.00000000e+00f,
    2.29213469e-02f, 0.00000000e+00f, -1.49720535e-02f, 0.00000000e+00f,
    9.56558679e-03f, 0.00000000e+00f, -5.86633996e-03f, 0.00000000e+00f,
    3.39305781e-03f, 0.00000000e+00f, -1.80075410e-03f, 0.00000000e+00f,
    8.44199816e-04f, 0.00000000e+00f, -3.43387434e-04f
};

// Halfband polyphase structure: in kHalfbandTaps, every tap at an even index
// is nonzero, and every tap at an odd index is exactly 0.0 *except* the
// center tap (index kHbN/2 = 23, the largest coefficient, ~0.5). Concretely:
// taps[0,2,4,...,46] are nonzero (24 taps) and taps[23] is nonzero; the
// other 22 odd-indexed taps are all 0.0 (see the array above).
//
// HalfbandUp zero-stuffs the input (in, 0) before filtering each of the two
// output phases. Zero-stuffing means the "0" half of the interleaved history
// is *known* to be 0 without needing to store or read it, and the two
// filter phases only ever end up multiplying against one parity of taps:
//   out2[0] (phase using the just-arrived real sample at lag 0) hits only
//     the even-indexed taps, weighted by the last 24 real input samples.
//   out2[1] (the other phase) hits only the odd-indexed taps, all of which
//     are 0 except the center — so it collapses to a single delayed sample
//     times the center tap.
// HalfbandDown mirrors this: convolving the interleaved (in0, in1) sequence
// against the same taps means the even taps only ever see the in1 stream
// and the (lone nonzero) center tap only ever sees the in0 stream at one
// fixed lag.
//
// This lets both structs replace the O(kHbN) history shift + O(kHbN) MAC
// (done twice per process() call) with a small ring buffer (no per-sample
// data movement, just a moving write index) and ~kHbHalf+1 MACs instead of
// 2*kHbN, while matching the direct-form implementation this replaced to
// within float32 reassociation error (measured maxDiff ~1e-7) — see
// ReferenceHalfbandUp/ReferenceHalfbandDown and the equivalence test in
// tests/yellowjacket/test_wasp_utils.cpp.
inline constexpr int kHbCenter = kHbN / 2;           // 23: index of the sole nonzero odd tap
inline constexpr int kHbHalf = (kHbN + 1) / 2;        // 24: count of nonzero even-indexed taps
inline constexpr int kHbCenterDelay = kHbCenter / 2;  // 11: history lag reaching the center tap

struct HalfbandUp {
    // ring[j samples back from the most recent input] for j in [0, kHbHalf).
    float ring[kHbHalf] = {};
    int head = 0; // index in `ring` holding the most-recently-written sample

    void reset() { for (float& v : ring) v = 0.f; head = 0; }

    // Zero-stuff (in, 0) then filter each phase; 2x tap gain restores the
    // amplitude halved by zero-stuffing (unity-gain halfband filter).
    void process(float in, float* out2) {
        head = (head + 1 == kHbHalf) ? 0 : head + 1;
        ring[head] = in;

        // acc0 = sum over even tap indices 2*j of taps[2*j] * (input j
        // samples ago), walked backward from `head` with wraparound split
        // into two contiguous runs (no per-iteration modulo).
        float acc0 = 0.f;
        int j = 0;
        for (int idx = head; idx >= 0 && j < kHbHalf; --idx, ++j)
            acc0 += kHalfbandTaps[2 * j] * ring[idx];
        for (int idx = kHbHalf - 1; j < kHbHalf; --idx, ++j)
            acc0 += kHalfbandTaps[2 * j] * ring[idx];
        out2[0] = 2.f * acc0;

        int centerIdx = head - kHbCenterDelay;
        if (centerIdx < 0) centerIdx += kHbHalf;
        out2[1] = 2.f * kHalfbandTaps[kHbCenter] * ring[centerIdx];
    }
};

struct HalfbandDown {
    static constexpr int kN1 = kHbHalf;             // history depth for the in1 stream
    static constexpr int kN0 = kHbCenterDelay + 1;  // history depth for the in0 stream
    float ring1[kN1] = {};
    float ring0[kN0] = {};
    int head1 = 0, head0 = 0;

    void reset() {
        for (float& v : ring1) v = 0.f;
        for (float& v : ring0) v = 0.f;
        head1 = 0; head0 = 0;
    }

    // Filter at the up-rate, keep every 2nd (post-pair) output; unity-gain
    // filter, no amplitude compensation needed (no zero-stuffing here).
    float process(float in0, float in1) {
        head1 = (head1 + 1 == kN1) ? 0 : head1 + 1;
        ring1[head1] = in1;
        head0 = (head0 + 1 == kN0) ? 0 : head0 + 1;
        ring0[head0] = in0;

        float acc = 0.f;
        int j = 0;
        for (int idx = head1; idx >= 0 && j < kN1; --idx, ++j)
            acc += kHalfbandTaps[2 * j] * ring1[idx];
        for (int idx = kN1 - 1; j < kN1; --idx, ++j)
            acc += kHalfbandTaps[2 * j] * ring1[idx];

        int centerIdx = head0 - kHbCenterDelay;
        if (centerIdx < 0) centerIdx += kN0;
        acc += kHalfbandTaps[kHbCenter] * ring0[centerIdx];

        return acc;
    }
};

// Soft rail clamp: identity until within 0.3 V of a rail, tanh knee beyond.
inline float railClamp(float v, float vHi, float vLo) {
    constexpr float w = 0.3f;
    float hi = vHi - w, lo = -vLo + w;
    if (v > hi) return hi + w*tanhApprox((v - hi)/w);
    if (v < lo) return lo - w*tanhApprox((lo - v)/w);
    return v;
}

} // namespace wasp
