#pragma once
// wasp_dsp_utils.hpp — shared math for the Yellowjacket Wasp VCF core.
// Constants and derivations: docs/superpowers/specs/2026-07-15-yellowjacket-*.md
#include <cmath>
#include <algorithm>

namespace wasp {

// tanh approximant x*(27+x^2)/(27+9x^2), exact-valued and slope-continuous
// at the |x|=3 handoff to +/-1 (tanh(3)=0.995).
inline float tanhApprox(float x) {
    if (x >  3.f) return 1.f;
    if (x < -3.f) return -1.f;
    float x2 = x*x;
    return x*(27.f + x2)/(27.f + 9.f*x2);
}
// tanh(x)/x with the same regions; limit 1 at 0.
inline float tanhXdX(float x) {
    float ax = std::fabs(x);
    if (ax > 3.f) return 1.f/ax;
    float x2 = x*x;
    return (27.f + x2)/(27.f + 9.f*x2);
}

// H1(s) resonance-network pole-zero, Delta-Y closed form (research notes),
// bilinear-transformed at the internal rate. rho = resonance pot 0..1.
struct H1Coeffs { float beta0, beta1, alpha1; };
inline H1Coeffs computeH1(float rho, float fsInt) {
    constexpr float R3=27e3f, R4=27e3f, R13=1e6f, R14=1e3f, R15=100e3f,
                    Rres=50e3f, C7=0.22e-6f;
    float s1 = rho*Rres + R14, s2 = (1.f-rho)*Rres, s3 = R13 + R15;
    float tot = s1 + s2 + s3;
    float Ra = s1*s3/tot, Rb = s2*s3/tot, Rc = s1*s2/tot;
    float Za = Ra, Zc = Rc + R4;
    float b1 = R3*Rb*C7, b0 = R3;
    float a1 = C7*(Rb*(Za+Zc) + Za*Zc), a0 = Za + Zc;
    float K = 2.f*fsInt, d = a0 + a1*K;
    return { (b0 + b1*K)/d, (b0 - b1*K)/d, (a0 - a1*K)/d };
}

// One-pole DC blocker (~8 Hz default).
struct DcBlocker {
    float state = 0.f, a = 0.001f;
    void setSampleRate(float fs) { a = 1.f - std::exp(-2.f*float(M_PI)*8.f/fs); }
    void reset() { state = 0.f; }
    float process(float x) { float y = x - state; state += a*y; return y; }
};

// 47-tap FIR halfband pair (taps generated by tests/yellowjacket_ref, Task 1;
// 31 taps could not reach the 70 dB stopband — see fitted_constants.md).
// kHalfbandTaps: the 47-tap primary array from fitted_constants.md.
inline constexpr int kHbN = 47;
inline constexpr float kHalfbandTaps[kHbN] = {
    -3.43387434e-04f, 0.00000000e+00f, 8.44199816e-04f, 0.00000000e+00f,
    -1.80075410e-03f, 0.00000000e+00f, 3.39305781e-03f, 0.00000000e+00f,
    -5.86633996e-03f, 0.00000000e+00f, 9.56558679e-03f, 0.00000000e+00f,
    -1.49720535e-02f, 0.00000000e+00f, 2.29213469e-02f, 0.00000000e+00f,
    -3.50925691e-02f, 0.00000000e+00f, 5.58476697e-02f, 0.00000000e+00f,
    -1.01243801e-01f, 0.00000000e+00f, 3.16662350e-01f, 4.99950856e-01f,
    3.16662350e-01f, 0.00000000e+00f, -1.01243801e-01f, 0.00000000e+00f,
    5.58476697e-02f, 0.00000000e+00f, -3.50925691e-02f, 0.00000000e+00f,
    2.29213469e-02f, 0.00000000e+00f, -1.49720535e-02f, 0.00000000e+00f,
    9.56558679e-03f, 0.00000000e+00f, -5.86633996e-03f, 0.00000000e+00f,
    3.39305781e-03f, 0.00000000e+00f, -1.80075410e-03f, 0.00000000e+00f,
    8.44199816e-04f, 0.00000000e+00f, -3.43387434e-04f
};

// Simple shift-register FIR halfband pair (correctness over cleverness; the
// even-offset zero taps could be exploited to halve the multiply count, but
// N=47 direct-form convolution twice per audio sample is cheap enough here).
struct HalfbandUp {
    float hist[kHbN] = {};
    // Zero-stuff (in, 0) then filter each phase; 2x tap gain restores the
    // amplitude halved by zero-stuffing (unity-gain halfband filter).
    void process(float in, float* out2) {
        for (int i = kHbN - 1; i > 0; --i) hist[i] = hist[i - 1];
        hist[0] = in;
        float acc0 = 0.f;
        for (int i = 0; i < kHbN; ++i) acc0 += kHalfbandTaps[i] * hist[i];
        out2[0] = 2.f * acc0;

        for (int i = kHbN - 1; i > 0; --i) hist[i] = hist[i - 1];
        hist[0] = 0.f;
        float acc1 = 0.f;
        for (int i = 0; i < kHbN; ++i) acc1 += kHalfbandTaps[i] * hist[i];
        out2[1] = 2.f * acc1;
    }
};
struct HalfbandDown {
    float hist[kHbN] = {};
    // Filter at the up-rate, keep every 2nd (post-pair) output; unity-gain
    // filter, no amplitude compensation needed (no zero-stuffing here).
    float process(float in0, float in1) {
        for (int i = kHbN - 1; i > 0; --i) hist[i] = hist[i - 1];
        hist[0] = in0;
        for (int i = kHbN - 1; i > 0; --i) hist[i] = hist[i - 1];
        hist[0] = in1;
        float acc = 0.f;
        for (int i = 0; i < kHbN; ++i) acc += kHalfbandTaps[i] * hist[i];
        return acc;
    }
};

// Soft rail clamp: identity until within 0.3 V of a rail, tanh knee beyond.
inline float railClamp(float v, float vHi, float vLo) {
    constexpr float w = 0.3f;
    float hi = vHi - w, lo = -vLo + w;
    if (v > hi) return hi + w*tanhApprox((v - hi)/w);
    if (v < lo) return lo - w*tanhApprox((lo - v)/w);
    return v;
}

} // namespace wasp
